### PR TITLE
Milestone 2: Capture NVDA speech output

### PR DESCRIPTION
**Pull request by jkva**

### CODE REVIEW

**Comment by jkva** [comment]
@jscholes currently for this to work, you'll need to set the synth driver in your NVDA to use the "Capture speech" synth.

**Comment by sinabahram** [comment]
Does that synth generate speech as a passthrough? If not, its a nonstarter.

**Comment by jkva** [comment]
> Does that synth generate speech as a passthrough? If not, its a nonstarter.

It's a piggyback synth on top of eSpeak, so in all respects behave as a regular speech synth. Does that answer your question?

**Comment by sinabahram** [comment]
It does, yes. Thank you for that, sir. I wish there was a way to tell it to use any existing synthesizer in NVDA already so that one is not stuck with the truly terrible experience that is eSpeak, perhaps one of the worst sounding TTS engines out there, but that's hardly a critical issue, and just a strong preference from me, and presumably from James too.

**Comment by jkva** [comment]
@sinabahram @jscholes I've figured out how to pass-through to a synth at will (well, within the default NVDA install) such as oneCore, sapi5 or MSSP. Those sound quite different from eSpeak. This suggests that as an enhancement we could make the "passthrough synth" a configuration setting post-MVP.

**Review by jscholes — APPROVED** [review]

**Pull request merged**
